[profile.default]
solc-version = "0.8.26"
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["SliceCore", "CrossChainVault", "ERC20"]
evm_version = "cancun"

[fuzz]
runs = 1000
seed = '0x2'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
